- name: Add item to yaml file at correct indentation level
  gather_facts: 'no'
  hosts: localhost
  tasks:
   - name: Add item to yaml file at correct indentation level
     lineinfile:
       backup: 'no'
       backrefs: 'yes'
       state: present
       path: /home/vbass/my.yml
       regexp: '^(\s*)[#]?{{ item.search }}(.*)'
       line: '\1{{ item.search }}\2\n\1{{ item.add }}'
     with_items:
       - { search: 'key2', add: 'key3: INSvalue3' }
       - { search: '- cat', add: '- deer' }

# yaml-file "my.yml":
# root:
#   child1:
#     key1: NEWvalue1
#     key2: NEWvalue2
#   arrays:
#     - animals
#         - bear
#         - cat
#         - dog
#         - heffalump
#     - servers
#         - www.google.com
#         - www.redhat.com

yaml-file "my.yml":
root:
  child1:
    key1: NEWvalue1
    key2: NEWvalue2
  arrays:
    - animals
        - bear
        - cat
        - dog
        - heffalump
    - servers
        - www.google.com
        - www.redhat.com
