- name: Replace values in json file
  gather_facts: 'no'
  hosts: localhost
  tasks:
   - name: Replace values in json file
     lineinfile:
        backup: 'no'
        backrefs: 'yes'
        state: present
        path: ./appsettings.json
        regexp: '^(\s*)[#]?{{ item.search }}(: )*'
        line: '\1{{ item.replace }}'
     with_items:
        # - { search: '\- elephant', replace: '- heffalump' }
        - { search: '\"urls": "http://0.0.0.0:54000",', replace: '"urls": "http://0.0.0.0:54001",' }
