- name: Replace values in yaml file
  gather_facts: 'no'
  hosts: localhost
  tasks:
   - name: Replace values in yaml file
     lineinfile:
        backup: 'no'
        backrefs: 'yes'
        state: present
        path: ./my.yml
        regexp: '^(\s*)[#]?{{ item.search }}(: )*'
        line: '\1{{ item.replace }}'
     with_items:
        - { search: 'key1', replace: 'key1: NEWvalue1' }
        - { search: 'key2', replace: 'key2: NEWvalue2' }
        - { search: '\- elephant', replace: '- heffalump' }
        - { search: '\- www.ansible.com', replace: '- www.redhat.com' }



# yaml- file "my.yml":
# root:
#   child1:
#     key1: value1
#     #key2: value2
#   arrays:
#     - animals
#         - bear
#         - cat
#         - dog
#         #- elephant
#     - servers
#         - www.google.com
#         - www.ansible.com
